version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_socios
    environment:
      MYSQL_ROOT_PASSWORD: "3564"  # Contraseña del usuario root
      MYSQL_DATABASE: "pena_socios"     # Base de datos inicial
    ports:
      - "3307:3306"  # Cambia el puerto en tu máquina (3307) para evitar conflicto con otros procesos
    volumes:
      - ./data/mysql:/var/lib/mysql  # Persistencia de datos

  ktor:
    build: .  # Esto indica que debe construir la imagen desde el Dockerfile en el directorio actual
    container_name: ktor_socios
    depends_on:
      - mysql  # Asegura que MySQL se inicie antes de Ktor
    ports:
      - "8081:8081"  # Mapea el puerto de Ktor al puerto de tu máquina
    environment:
      - DB_URL=jdbc:mysql://mysql:3307/pena_socios  # URL de conexión de MySQL
      - DB_USER=root
      - DB_PASSWORD=3564  # Contraseña de root en MySQL
